--CREATE the RO f_bdt_date 

CREATE OR REPLACE TYPE Date_Type AS OBJECT(
  Trade_Date Varchar(15),
  MEMBER FUNCTION getTradedate RETURN VARCHAR,
  MEMBER FUNCTION getJDS RETURN CHAR,
  MEMBER FUNCTION getJDA RETURN VARCHAR,
  MEMBER FUNCTION getMois RETURN VARCHAR,
  MEMBER FUNCTION getTrimestre RETURN CHAR,
  MEMBER FUNCTION getSemaine RETURN VARCHAR
);
/

CREATE TYPE BODY Date_Type
IS
MEMBER FUNCTION getTradedate RETURN VARCHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
MEMBER FUNCTION getJDS RETURN CHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
MEMBER FUNCTION getJDA RETURN VARCHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
MEMBER FUNCTION getMois RETURN VARCHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
MEMBER FUNCTION getTrimestre RETURN CHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
MEMBER FUNCTION getSemaine RETURN VARCHAR
  IS
  BEGIN
    RETURN SELF.Trade_Date;
  END;
END;
/

CREATE TABLE f_bdt_date OF Date_Type(
  CONSTRAINT pk_Trade_Date PRIMARY KEY (Trade_Date)
);

ALTER TABLE f_bdt_date ADD CONSTRAINT check_Date CHECK(REGEXP_LIKE(Trade_Date,'^\d{4}-\d{2}-\d{2}$'));

