CREATE TABLE f_dw_magasin(
  MAGASIN_ID VARCHAR(4),
  RAYONNAGE VARCHAR(10),
  BESTSELLER CHAR(1),
  RAYON_RECENT CHAR(1),
  DPT_NAME VARCHAR(50),
  DPT_POPULATION NUMBER(10)
);

CREATE UNIQUE INDEX f_dw_magasin_index ON f_dw_magasin(MAGASIN_ID);

ALTER TABLE f_dw_magasin
	ADD CONSTRAINT pk_f_dw_magasin PRIMARY KEY (MAGASIN_ID);

